apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: go-instrumentation
  namespace: demo
spec:
  exporter:
    endpoint: http://otel-collector-collector.opentelemetry-operator-system:4317
  propagators:
    - tracecontext
    - baggage
  nginx:
    image: ghcr.io/open-telemetry/opentelemetry-operator/autoinstrumentation-apache-httpd:1.0.4
    configFile: /etc/nginx/nginx.conf
    env:
      - name: OTEL_SERVICE_NAME
        value: nginx-gateway
