manager:
  collectorImage:
    repository: ghcr.io/open-telemetry/opentelemetry-collector-releases/opentelemetry-collector-k8s
  autoInstrumentation:
    go:
      enabled: true
  extraArgs:
    - --enable-nginx-instrumentation

admissionWebhooks:
  certManager:
    enabled: false
  autoGenerateCert:
    enabled: true
