server:
  extraFlags:
    - "web.enable-remote-write-receiver"
    - "enable-feature=exemplar-storage"

alertmanager:
  enabled: false

kube-state-metrics:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false
